db:
  image: mysql:5.7
  volumes:
    - db_data:/var/lib/mysql
    - ./structure.sql:/docker-entrypoint-initdb.d/dump.sql
  ports:
    - 3306:3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 1
    MYSQL_DATABASE: url_shortener
